### ISSUE TITLE
issue with latest release

### ISSUE THREAD

**Issue by jurand-cpu** [MagicCheese1/Damage-Indicator#23]
[16:47:50] [Server thread/INFO]: [DamageIndicator] Enabling DamageIndicator v1.3.7
[16:47:50] [Server thread/ERROR]: Error occurred while enabling DamageIndicator v1.3.7 (Is it up to date?)
java.lang.RuntimeException: Failed to create version specific server accessor
	at com.github.magiccheese1.damageindicator.Main.onEnable(Main.java:56) ~[DamageIndicator.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-201]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-201]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-201]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:47:50] [Server thread/INFO]: [DamageIndicator] Disabling DamageIndicator v1.3.7

**Comment by MagicCheese1** [comment]
Damage Indicator doesn't yet support Spigot/Paper 1.20.2!
Will fix soon

**Comment by MagicCheese1** [comment]
Fixed in 1.3.8
