### ISSUE TITLE
1.17 Bug?

### ISSUE THREAD

**Issue by BenjaminHoegh** [MagicCheese1/Damage-Indicator#3]
Not 100% sure this has todo with your plugin or papermc but you probably know more about it than me

ProtocolLib v4.7.0-SNAPSHOT-b520
Paper version git-Paper-"47605b8" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

Console:
```
21.06 14:34:23 [Server] ERROR Could not pass event EntityDamageByEntityEvent to DamageIndicator v1.1.4
21.06 14:34:23 [Server] INFO com.comphenix.protocol.reflect.FieldAccessException: No field with type [I exists in class PacketPlayOutEntityDestroy.
21.06 14:34:23 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
21.06 14:34:23 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
21.06 14:34:23 [Server] INFO at com.github.magiccheese1.damageindicator.EntityHider.hideEntity(EntityHider.java:277) ~[?:?]
21.06 14:34:23 [Server] INFO at com.github.magiccheese1.damageindicator.EntityHider.toggleEntity(EntityHider.java:240) ~[?:?]
21.06 14:34:23 [Server] INFO at com.github.magiccheese1.damageindicator.InvisibleArmorStand.lambda$accept$0(InvisibleArmorStand.java:26) ~[?:?]
21.06 14:34:23 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
21.06 14:34:23 [Server] INFO at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
21.06 14:34:23 [Server] INFO at com.github.magiccheese1.damageindicator.InvisibleArmorStand.accept(InvisibleArmorStand.java:24) ~[?:?]
21.06 14:34:23 [Server] INFO at com.github.magiccheese1.damageindicator.InvisibleArmorStand.accept(InvisibleArmorStand.java:8) ~[?:?]
21.06 14:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.addEntity(CraftWorld.java:2025) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.spawn(CraftWorld.java:2035) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.spawn(CraftWorld.java:1599) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at com.github.magiccheese1.damageindicator.DamageIndicatorListener.entityDamageByEntity(DamageIndicatorListener.java:93) ~[?:?]
21.06 14:34:23 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor52.execute(Unknown Source) ~[?:?]
21.06 14:34:23 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1085) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:971) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:927) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1117) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2034) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1350) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.world.entity.monster.EntityZombie.damageEntity(EntityZombie.java:315) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.world.entity.player.EntityHuman.attack(EntityHuman.java:1258) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.level.EntityPlayer.attack(EntityPlayer.java:2002) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2415) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2342) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"47605b8"]
21.06 14:34:23 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by MagicCheese1** [comment]
I wasn't able to reproduce this. What's your ShowToDamager set to in the config?

**Comment by BenjaminHoegh** [comment]
default settings

**Comment by MagicCheese1** [comment]
Can you please give me exact steps how to reproduce this ?

**Comment by BenjaminHoegh** [comment]
still trying to debug it. for some reason its only on my remote server the issue apper

**Comment by BenjaminHoegh** [comment]
```
[21:25:11 WARN]: [ProtocolLib] [PacketFilterManager] [DamageIndicator] Unsupported server packet in current Minecraft version: UPDATE_ENTITY_NBT[PLAY, SERVER, 253, classNames: [net.minecraft.network.protocol.game.PacketPlayOutUpdateEntityNBT, net.minecraft.network.protocol.game.ClientboundUpdateEntityNBTPacket] (unregistered)]
[21:25:11 WARN]: [ProtocolLib] [PacketFilterManager] [DamageIndicator] Unsupported server packet in current Minecraft version: BED[PLAY, SERVER, 251, classNames: [net.minecraft.network.protocol.game.PacketPlayOutBed, net.minecraft.network.protocol.game.ClientboundBedPacket, net.minecraft.network.play.server.SPacketUseBed] (unregistered)]
[21:25:11 WARN]: [ProtocolLib] [PacketFilterManager] [DamageIndicator] Unsupported server packet in current Minecraft version: COMBAT_EVENT[PLAY, SERVER, 247, classNames: [net.minecraft.network.protocol.game.PacketPlayOutCombatEvent, net.minecraft.network.protocol.game.ClientboundCombatEventPacket] (unregistered)]
```
