### ISSUE TITLE
Error on PaperMC 1.20.6

### ISSUE THREAD

**Issue by viandwi24** [MagicCheese1/Damage-Indicator#31]
this is error when starting papermc server
```
[01:38:21 INFO]: [DamageIndicator] Enabling DamageIndicator v2.0.1
[01:38:21 ERROR]: Error occurred while enabling DamageIndicator v2.0.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at DamageIndicator.jar/io.github.magiccheese1.damageindicator.DamageIndicatorImpl.onEnable(DamageIndicatorImpl.java:54) ~[DamageIndicator.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:38:21 INFO]: [DamageIndicator] Disabling DamageIndicator v2.0.1
```

my installed plugins :
```
> plugins
[01:43:57 INFO]: Server Plugins (7):
[01:43:57 INFO]: Bukkit Plugins:
[01:43:57 INFO]:  - BetterMessages, BlueMap, DamageIndicator, InteractionVisualizer, LuckPerms, PluginPortal, WTab
```

<details>
  <summary>full log is :</summary>
<code>
java -Xmx1536M -Xms1536M -jar paper-1.20.6-138.jar nogui
Starting org.bukkit.craftbukkit.Main
System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-Ubuntu-1ubuntu122.04.1) Host: Linux 5.15.0-25-generic (amd64)
Loading libraries, please wait...
[01:37:45 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[01:37:47 INFO]: Loaded 1175 recipes
[01:37:48 INFO]: Loaded 1276 advancements
[01:37:48 INFO]: Starting minecraft server version 1.20.6
[01:37:48 INFO]: Loading properties
[01:37:48 INFO]: This server is running Paper version 1.20.6-138-master@906df69 (2024-06-10T06:32:15Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[01:37:49 INFO]: Server Ping Player Sample Count: 12
[01:37:49 INFO]: Using 4 threads for Netty based IO
[01:37:50 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[01:37:50 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[01:37:51 INFO]: Default game type: SURVIVAL
[01:37:51 INFO]: Generating keypair
[01:37:51 INFO]: Starting Minecraft server on *:25565
[01:37:51 INFO]: Using epoll channel type
[01:37:51 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[01:37:51 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[01:37:52 INFO]: [SpigotLibraryLoader] [PluginPortal] Loading 2 libraries... please wait
[01:37:52 INFO]: [SpigotLibraryLoader] [PluginPortal] Loaded library /home/viandwi24/mc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
[01:37:52 INFO]: [SpigotLibraryLoader] [PluginPortal] Loaded library /home/viandwi24/mc/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
[01:37:52 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.131
[01:37:53 INFO]: [BlueMap] Loading server plugin BlueMap v3.21
[01:37:53 INFO]: [InteractionVisualizer] Loading server plugin InteractionVisualizer v1.18.9.0
[01:37:53 INFO]: [PluginPortal] Loading server plugin PluginPortal v1.5.0
[01:37:53 INFO]: [BetterMessages] Loading server plugin BetterMessages v3.3.2
[01:37:53 INFO]: [DamageIndicator] Loading server plugin DamageIndicator v2.0.1
[01:37:53 INFO]: [WTab] Loading server plugin WTab v1.1.3-SNAPSHOT
[01:37:53 INFO]: Server permissions file permissions.yml is empty, ignoring it
[01:37:53 INFO]: [LuckPerms] Enabling LuckPerms v5.4.131
[01:37:53 INFO]:         __
[01:37:53 INFO]:   |    |__)   LuckPerms v5.4.131
[01:37:53 INFO]:   |___ |      Running on Bukkit - Paper
[01:37:53 INFO]:
[01:37:53 INFO]: [LuckPerms] Loading configuration...
[01:37:54 INFO]: [LuckPerms] Loading storage provider... [H2]
[01:37:54 INFO]: [LuckPerms] Loading internal permission managers...
[01:37:54 INFO]: [LuckPerms] Performing initial data load...
[01:37:54 INFO]: [LuckPerms] Successfully enabled. (took 1722ms)
[01:37:54 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[01:37:54 WARN]: The server will make no attempt to authenticate usernames. Beware.
[01:37:54 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[01:37:54 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[01:37:54 INFO]: Preparing level "world"
[01:37:55 INFO]: Preparing start region for dimension minecraft:overworld
[01:37:57 INFO]: Time elapsed: 1964 ms
[01:37:57 INFO]: Preparing start region for dimension minecraft:the_nether
[01:37:58 INFO]: Time elapsed: 360 ms
[01:37:58 INFO]: Preparing start region for dimension minecraft:the_end
[01:37:58 INFO]: Time elapsed: 111 ms
[01:37:58 INFO]: [BlueMap] Enabling BlueMap v3.21
[01:37:58 INFO]: [BlueMap] Loading...
[01:37:58 INFO]: [InteractionVisualizer] Enabling InteractionVisualizer v1.18.9.0
[01:37:59 INFO]: [BlueMap] Loading resources...
[01:38:01 INFO]: [BlueMap] Loading textures...
[01:38:02 INFO]: [BlueMap] Baking resources...
[01:38:02 INFO]: [BlueMap] Resources loaded.
[01:38:02 INFO]: [BlueMap] Loading world '2d75c241-f8bb-41b6-af00-b033354fed81' (/home/viandwi24/mc/world_the_end/DIM1)...
[01:38:02 INFO]: [BlueMap] Initializing Storage: 'file' (Type: FILE)
[01:38:02 INFO]: [BlueMap] Loading map 'world_the_end'...
[01:38:03 INFO]: [BlueMap] Loading world '80b862c8-6c7f-459b-9b3a-3be2f70a9110' (/home/viandwi24/mc/world)...
[01:38:03 INFO]: [BlueMap] Loading map 'world'...
[01:38:03 INFO]: [BlueMap] Loading world '3bf10902-c9f3-473a-8656-3342fcc62234' (/home/viandwi24/mc/world_nether/DIM-1)...
[01:38:03 INFO]: [BlueMap] Loading map 'world_nether'...
[01:38:03 INFO]: [BlueMap] WebServer bound to all network interfaces on port 8100
[01:38:03 INFO]: [BlueMap] WebServer started.
[01:38:03 INFO]: [BlueMap] Loaded!
[01:38:05 INFO]: [InteractionVisualizer] Opened Sqlite database successfully
[01:38:07 INFO]: [InteractionVisualizer] InteractionVisualizer has been enabled!
[01:38:07 INFO]: [PluginPortal] Enabling PluginPortal v1.5.0
[01:38:15 INFO]: [BetterMessages] Enabling BetterMessages v3.3.2
[01:38:21 WARN]: java.io.IOException: Failed to check for updates
[01:38:21 WARN]:        at BetterMessages-3.3.2.jar//com.imjustdoom.bettermessages.UpdateChecker.checkUpdates(UpdateChecker.java:19)
[01:38:21 WARN]:        at BetterMessages-3.3.2.jar//com.imjustdoom.bettermessages.BetterMessages.onEnable(BetterMessages.java:62)
[01:38:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[01:38:21 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[01:38:21 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[01:38:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[01:38:21 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604)
[01:38:21 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553)
[01:38:21 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[01:38:21 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[01:38:21 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323)
[01:38:21 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
[01:38:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[01:38:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[01:38:21 WARN]: [BetterMessages] The above error will not affect the plugins abilities. It just failed to check for an update. You can disable this in the config file
[01:38:21 INFO]: [DamageIndicator] Enabling DamageIndicator v2.0.1
[01:38:21 ERROR]: Error occurred while enabling DamageIndicator v2.0.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at DamageIndicator.jar/io.github.magiccheese1.damageindicator.DamageIndicatorImpl.onEnable(DamageIndicatorImpl.java:54) ~[DamageIndicator.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:38:21 INFO]: [DamageIndicator] Disabling DamageIndicator v2.0.1
[01:38:21 INFO]: [WTab] Enabling WTab v1.1.3-SNAPSHOT
[01:38:21 INFO]: [WTab] ------------------------------------
[01:38:21 INFO]: [WTab] Enabled DataCaching!
[01:38:21 INFO]: [WTab] This is a new feature and is still in beta! It should use less resources than before.
[01:38:21 INFO]: [WTab] If this cause any problems, please contact me on Discord: TheSkyScout#0000
[01:38:21 INFO]: [WTab] ------------------------------------
[01:38:21 INFO]: [WTab] Starting Tablist
[01:38:24 WARN]: [WTab] There is a new update available!
[01:38:30 WARN]: [WTab] New Version: WTab-1.1.3-SNAPSHOT.jar"
[01:38:30 INFO]: Running delayed init tasks
[01:38:30 INFO]: Done (42.083s)! For help, type "help"
[01:38:30 INFO]: Timings Reset
[01:38:30 INFO]: [InteractionVisualizer] Downloading and extracting latest Language files...
[01:38:31 INFO]: [InteractionVisualizer] Sucessfully downloaded the latest Language files!
</code>
</details>

**Comment by Jack1424** [comment]
I'm having the same issue. Running paper 1.20.6.

**Comment by MagicCheese1** [comment]
Damage Indicator doesn't work on Minecraft 1.20.6 currently. Will fix ASAP
