### ISSUE TITLE
Error with excelent enchants

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [MagicCheese1/Damage-Indicator#37]
[14:49:11 ERROR]: Could not pass event AreaEffectCloudApplyEvent to DamageIndicator v2.1.3
java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionData.getType()" because the return value of "org.bukkit.entity.AreaEffectCloud.getBasePotionData()" is null
        at DamageIndicator.jar/io.github.magiccheese1.damageindicator.BukkitEventListener.areaEffectCloudApply(BukkitEventListener.java:122) ~[DamageIndicator.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor493.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callAreaEffectCloudApplyEvent(CraftEventFactory.java:1882) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.world.entity.AreaEffectCloud.tick(AreaEffectCloud.java:281) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1804) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.

**Comment by MagicCheese1** [comment]
Great catch! Will fix ASAP! Do you have some additional info? When does this error come up? etc.

**Comment by TDMidkwhatisxd** [comment]
I saw it spamming in console, i does not affect gameplay, its just annoying, i think its an enchant that make a potion cloud or something

**Comment by MagicCheese1** [comment]
fixed as of v2.1.4
